# pull official base image
FROM node:lts-alpine as builder

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json .
RUN npm install --legacy-peer-deps

# add app
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html