export const ACCION = {
     SET_FORM_EDITION: "SET_FORM_EDITION",
     LISTAR_DATOS_AUTH: "LISTAR_DATOS_AUTH",
     LISTAR_DATOS_GENERAL: "LISTAR_DATOS_GENERAL",
     SET_LISTA_CONVOCATORIAS_PRG: "SET_LISTA_CONVOCATORIAS_PRG"
}