export const ACCION = {
     LISTAR_ITEM: "LISTAR_ITEM",
     SET_LISTA_CONVOCATORIAS_PROGRAMA: "SET_LISTA_CONVOCATORIAS_PROGRAMA",
     SET_LISTA_SIMULACROS_PROGRAMA: "SET_LISTA_SIMULACROS_PROGRAMA"

}